#%RAML 1.0 DataType
type: object
properties:
  name: string # cli_des ABEL CANO
  id: string # co_cli 0627
  x_rif: string # rif
  type: string # contribu 0 # esto es lo mismo que nivel? Si no, agregarlo.
  x_contribu: string # tipo C
  zone: string # co_zon 000004
  segment: string # co_seg 130505
  account: string # co_ingr 130505
  address_1: string # direc1 CARRERA 80A # 32 - 63 NUEVA VILLA DE ABURRA BARRIO BELEN MANZANA F BLOQUE 5 APT 403
  address_2: string # direc2
  city: string # ciudad
  country: string # co_pais CO
  x_respons: string # respons
  email: string # email
  telephone: number # telefonos 2503226
  fax: number # fax
  x_zip: string # zip 5%DSCTO
  website: string # website
  seller: string # co_ven 000001
  registered_at: date # fecha_reg Jul 30 2012 1200AM
  x_sincredito: boolean # sincredito 0
  x_mont_cre: number # mont_cre 0.00
  x_plaz_pag: number # plaz_pag 0
  x_desc_ppago: number # desc_ppago 0.00
  x_desc_glob: number # desc_glob 0.00
  monday: boolean # lunes 0
  tuesday: boolean # martes 0
  wednesday: boolean # miercoles 0
  thursday: boolean # jueves 0
  friday: boolean # viernes 0
  saturday: boolean # sabado 0
  sunday: boolean # domingo 0
  visit_frequency: number # frecu_vist
  comment: string # comentario
