#%RAML 1.0 DataType
type: object
properties:
  name: string # ven_des
  id: string # co_ven
  id_number: number # cedula
  type: string # tipo
  address_1: string # direc1
  email: string # email
  registered_at: date # fecha_reg Jul 30 2012 1200AM
  comment: string # comentario
  x_comision_v: string
  x_comision: string
  x_fun_ven: string
  x_fun_cob: string
  telephone: number # telefonos 2503226
